# Generated by Django 3.2.22 on 2023-10-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20231015_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='num_users',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
